### ISSUE TITLE
Publish to Maven Central Repository

### ISSUE THREAD

**Issue by mfvanek** [DarrMirr/dbchange#1]
Could you please publish DbChange to https://mvnrepository.com/repos/central ?

See https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by DarrMirr** [comment]
@mfvanek thank you for your suggestion. Get to work this issue.

**Comment by DarrMirr** [comment]
@mfvanek done. [DbChange on Maven central repository](https://repo1.maven.org/maven2/io/github/darrmirr/dbchange/)
